title: Andrew W. Brooks
email: awbrooks19@gmail.com
description: "Developing innovative data science tools for analysis, visualization, and automation."
baseurl: "" # the subpath base
url: "https://awbrooks.github.io/" 
github_username:  awbrooks

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

social_links:
  linkedin: https://www.linkedin.com/in/awbrooks19/

collections:
  projects:
    output: true
  tutorials:
    output: true
    
# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
